version: '3.9'

networks:
  webapi-network:
    driver: bridge

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=zubriq
      - POSTGRES_PASSWORD=zubriq

    #image: mcr.microsoft.com/mssql/server:2019-latest
    #ports:
    #  - "1433:1433"
    #environment:
    #  ACCEPT_EULA: "Y"
    #  SA_PASSWORD: "AN1m4l1@Ch1Pp3r!"
    networks:
      - webapi-network
    #healthcheck:
    #  test: ["CMD-SHELL", "pgrep sqlservr"]
    #  interval: 3s
    #  timeout: 5s
    #  retries: 100
    restart: always
    
  webapi:
    image: olympproject:latest
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__PostgreSQL: "Host=database;Port=5432;Database=animal-chipization;Username=zubriq;Password=zubriq"
    networks:
      - webapi-network
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --fail http://webapi:8080/health || exit 1"]
    #  interval: 3s
    #  timeout: 5s
    #  retries: 100
    depends_on:
      - database
    #  database:
    #    condition: service_healthy
    restart: always
    
  tests:
    image: mrexpen/planet_olymp_phase2
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    #  webapi:
    #    condition: service_healthy
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
    networks:
      - webapi-network
    restart: always