version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AN1m4l1@Ch1Pp3r!"

  webapi:
    image: olympproject:latest
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      ConnectionStrings__Default: "Server=database;Database=animal-chipization;User Id=sa;Password=AN1m4l1@Ch1Pp3r!;"

  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: 1
