version: '3.9'

networks:
  webapi-network:
    driver: bridge

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AN1m4l1@Ch1Pp3r!"
    networks:
      - webapi-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr"]
      interval: 3s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    
  webapi:
    image: olympproject:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Testing: "Server=database;Database=animal-chipization;User Id=sa;Password=AN1m4l1@Ch1Pp3r!;"
    networks:
      - webapi-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://webapi:8080/health || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 30
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      webapi:
        condition: service_healthy
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
    networks:
      - webapi-network
    restart: unless-stopped